#!/bin/sh

# ci_post_clone.sh — Runs after Xcode Cloud clones the repository.
# Generates Secrets.swift (which is gitignored) so the build can compile.
# If the ANTHROPIC_API_KEY environment variable is set in Xcode Cloud,
# that value is used; otherwise a placeholder is inserted.

set -e

SECRETS_FILE="${CI_PRIMARY_REPOSITORY_PATH}/RockinBod/Utilities/Secrets.swift"

echo "Generating Secrets.swift for Xcode Cloud build..."

API_KEY="${ANTHROPIC_API_KEY:-}"

cat > "$SECRETS_FILE" << EOF
import Foundation

// Auto-generated by ci_post_clone.sh — do not commit.

enum Secrets {
    static let anthropicAPIKey = "${API_KEY}"
}
EOF

echo "Secrets.swift generated at ${SECRETS_FILE}"
